# Generated by Django 6.1.1 on 2026-09-19 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_jobapplication_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobapplication",
            name="job_domain",
        ),
    ]
